title: ROSA - Robot Operating System Agent
description: ROSA is an AI Agent designed to interact with ROS1- and ROS2-based robotics systems using natural language queries. ROSA helps robot developers inspect, diagnose, understand, and operate robots.
theme: just-the-docs

url: https://robroyce.github.io/rosa.github.io

aux_links:
  ROSA: https://github.com/nasa-jpl/rosa
